version: '3.8'
services:  

#   Setup server container
  server:   
    build: ./server
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - backend
      - frontend
    stdin_open: true
    tty: true

#   Setup client container
  client:
    depends_on:
      - server
    build:
      context: ./client
    ports:
      - 80:3000
    networks:
      - frontend  

networks:
  backend:
  frontend: